### ISSUE TITLE
Unable to achieve VizWiz accuracy of 54.72 as reported in the paper

### ISSUE THREAD

**Issue by xymtxwd** [facebookresearch/pythia#129]
## ❓ Questions and Help
Hi, 

Thanks a lot for sharing the codes and models. The performance is amazing. However, I am unable to obtain the accuracy of 54.72 on VizWiz as reported in your paper on Arxiv. I can only achieve 54.22 accuracy. I was wondering is there anything I might have missed? Or is this a typo?

Thanks again.

**Comment by apsdehal** [comment]
Hi,

The model trained in the paper is v0.1 branch which is trained on more data (including Visual Dialog, Visual Genome and VQA). That's why you see some gap in the final accuracy after transferring. I will keep this open for now as there isn't a way to reproduce it in v0.3 except taking model from v0.1 and running it.

**Comment by xymtxwd** [comment]
Hi,

Thanks for the comments. However in the paper, it says:

VizWiz Accuracy
BAN[25] 51.40
Pythia v0.3 (Ours) 54.72

I think here it suggests it's v0.3 branch which achieves 54.72 accuracy. Should this be v0.1 (a typo?) Thank you very much.

**Comment by apsdehal** [comment]
We do have imdbs, so it is easy to use it. But, we don't yet have them released in a manner that it is usable by end users.

**Comment by apsdehal** [comment]
I have updated my comment above.

**Comment by xymtxwd** [comment]
Hi,

Thanks a lot for sharing the information. That makes sense to me. I'm closing this - thanks again.
