### ISSUE TITLE
Do Pythia support training on other language beside English?

### ISSUE THREAD

**Issue by tienthegainz** [facebookresearch/pythia#137]
## ❓ Questions and Help
As the title desscribed, I want to train the model for my VQA dataset in Vietnamese. Does the OCR part and Embedding part support Vietnamese. Or I have to customize it myself?

**Comment by apsdehal** [comment]
It is possible to do this. You will have to change three things: 
- Since, we don't have a public version of Rosetta OCR model, I will suggest you to extract out the OCR tokens using Google Cloud Vision API. Create an imdb for your questions in same format as the one for TextVQA with the OCR tokens you just extracted out. Checkout https://cloud.google.com/vision/docs/ocr (specifically 'Specify a language part') and https://cloud.google.com/vision/docs/languages
- Instead of using fasttext english bin use Vietnamese one available at https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.vi.300.bin.gz (Clicking on the link will download it)
- Change the configuration files accordingly to use the path to the bin you just downloaded.

**Comment by tienthegainz** [comment]
Thanks man. I'll give it a try
