### ISSUE TITLE
Help: Scores for Answers

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/pythia#187]
## ❓ Questions and Help
While reading about [VQA evaluation metric](https://visualqa.org/evaluation.html) what I understand is that an answer gets a score of 1 if at least 3 human annotators gave the same answer. 

But in https://github.com/facebookresearch/pythia/blob/37b2dc5d745fd752ba0c574e246856f03e49fb6d/pythia/tasks/processors.py#L639 where scores for each unique answer is computed , it is done in a different manner. Can you please help me understand why `avg_acc ` is computed here instead ?

For example if the 10 ground truth answer indices are `[ 1, 2, 3, 1 ,2, 3, 1, 2, 3, 1]` , all of the unique answers , i.e, 1, 2 and 3 should get a score of 1.0. Instead this function yields scores 1.0, 0.9 and 0.9 respectively.

-----------------------------------------------
```

for answer in unique_answers:
    hits = [item for item in gt_answers if item[1] == answer]
    acc = min(1, float(len(hits)) / 3)
    scores[answer] = acc
```
Instead would not the above logic suffice to compute the scores. 

I understand that your implementation is based on this statement in the  VQA portal -  _In order to be consistent with ‘human accuracies’, machine accuracies are averaged over all 10 choose 9 sets of human annotators._ 
But I am unable to understand the rationale behind it

**Comment by apsdehal** [comment]
Apologies for the late reply. I have been traveling recently.

The 10 choose 9 sets of human annotators concept is to make sure outliers don't affect the scores. That's why each of the answers are evaluated on 9 different set where you remove on answer.

What you are saying will also work. But change `acc = min(1, float(len(hits)) / 3)` to `acc = min(1, 0.3 * len(hits))`. I don't remember from the top of the head why I shifted to exact implementation of the metric but it was something related to dynamic answer space in LoRRA.
