### ISSUE TITLE
Result of LoRRA on VQA2.0

### ISSUE THREAD

**Issue by LousyLory** [facebookresearch/pythia#99]
## ❓ Questions and Help
Hi, thanks a lot for addressing all the querries.

I know that LoRRA is SoTA for textVQA. Is it also SoTA for VQA2.0? I re-trained LoRRA for VQA2.0 (using the provided config file) and the test results are the following:

yes/no | 85.44
number | 48.5
other | 58.67
overall | 68.54

This is very similar to original Pythia results.

Thanks in advance!!

**Comment by apsdehal** [comment]
There might be differences due to number of GPUs being used. Our original config on 8 GPUs does lead to 69.21% for a single model performance which is better than Pythia. But I agree the border is a little blurry that's why we don't claim SoTA in paper and just say that LoRRA leads to performance improvements.

**Comment by LousyLory** [comment]
Cool, thanks!!
